baseurl = "https://maxence.maireaux.fr"
title = "Maxence Maireaux"
theme = "hugo-coder"
languagecode = "fr"
defaultcontentlanguage = "fr"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
author = "Maxence Maireaux"
info = "VP of Engineering | DevOps Engineer"
description = "John Doe's personal website"
keywords = "blog,developer,personal"
avatarurl = "images/avatar.jpg"
gravatar = "maxence@maireaux.fr"

favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"

since = 2019

enableTwemoji = true

colorScheme = "auto"
hidecolorschemetoggle = false

#customCSS = ["css/custom.css"]
#customSCSS = ["scss/custom.scss"]
#customJS = ["js/custom.js"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin fa-2x"
weight = 1
url = "https://www.linkedin.com/in/maxencemaireaux/"
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 2
url = "https://github.com/flemzord/"
[[params.social]]
name = "Twitter"
icon = "fa fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/flemzord/"
[[params.social]]
name = "Twitch"
icon = "fa fa-twitch fa-2x"
weight = 3
url = "https://twitch.tv/flemzord"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url  = "posts/"
#[[menu.main]]
#name = "About"
#weight = 2
#url = "about/"


# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
domain = "maxence.maireaux.fr"
serverURL = "plausible.flemzord.ovh" # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
